### ISSUE TITLE
Ошибка при загрузке логов

### ISSUE THREAD

**Issue by Nikiror** [YPermitin/YY.EventLogExportAssistant#40]
**Описание ошибки**
При попытке загрузки журнала в базе Clickhouse появляется ошибка парсинга 

Ошибка при экспорте данных.Критическая: False

Содержимое события:
{20200825002217,C,
{243a813b13a90,d3},0,1,2,14,3,I,"",0,
{"U"},"",1,1,1,1,0,
{2,1,1,2,1}
},
Информация об ошибке:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at YY.EventLogReaderAssistant.Helpers.EventLogRowPartLGFExtensions.Parse[T](EventLogRowPartLGF value, String[] sourceData)
   at YY.EventLogReaderAssistant.Helpers.EventLogRowPartLGFExtensions.Parse(EventLogRowPartLGF value, String[] sourceData)
   at YY.EventLogReaderAssistant.Models.RowData.FillByStringParsedData(EventLogLGFReader reader, String[] parseResult)
   at YY.EventLogReaderAssistant.LogParserLGF.Parse(String eventSource)
   at YY.EventLogReaderAssistant.EventLogLGFReader.ReadRowData(String sourceData)
   at YY.EventLogReaderAssistant.EventLogLGFReader.Read()
Ошибка при экспорте данных.Критическая: False

Содержимое события:
{20200825002217,C,
{243a813b13a90,d3},0,1,2,14,4,I,"",0,
{"U"},"",1,1,1,1,0,
{2,1,1,2,1}
},
Информация об ошибке:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at YY.EventLogReaderAssistant.Helpers.EventLogRowPartLGFExtensions.Parse[T](EventLogRowPartLGF value, String[] sourceData)
   at YY.EventLogReaderAssistant.Models.RowData.FillByStringParsedData(EventLogLGFReader reader, String[] parseResult)
   at YY.EventLogReaderAssistant.LogParserLGF.Parse(String eventSource)
   at YY.EventLogReaderAssistant.EventLogLGFReader.ReadRowData(String sourceData)
   at YY.EventLogReaderAssistant.EventLogLGFReader.Read()
Ошибка при экспорте данных.Критическая: False

Содержимое события:
{20200825002217,N,
{0,0},1,1,2,14,5,I,"",1,
{"S","Извлечение текста"},"",1,1,0,1,0,
{2,1,1,2,1}
},
Информация об ошибке:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at YY.EventLogReaderAssistant.Helpers.EventLogRowPartLGFExtensions.Parse[T](EventLogRowPartLGF value, String[] sourceData)
   at YY.EventLogReaderAssistant.Models.RowData.FillByStringParsedData(EventLogLGFReader reader, String[] parseResult)
   at YY.EventLogReaderAssistant.LogParserLGF.Parse(String eventSource)
   at YY.EventLogReaderAssistant.EventLogLGFReader.ReadRowData(String sourceData)
   at YY.EventLogReaderAssistant.EventLogLGFReader.Read()
Ошибка при экспорте данных.Критическая: False

**Информация для расследования:**
 - 8.3.16.1502
 - ClickHouse
 - Windows server 2016
 - Файл журнала регистрации по возможности

**Comment by YPermitin** [comment]
@Nikiror Ошибку воспроизвел и исправил в библиотеке чтения ЖР.
https://github.com/YPermitin/YY.EventLogReaderAssistant/tree/develop-restore

Сегодня обновлю библиотеки после дополнительного тестирования.

**Comment by YPermitin** [comment]
Ошибка испралена. Подтверждено.
